declare module 'global' {
   export default interface Repository {
        allow_forking: boolean;
        archive_url: string;
        archived: boolean;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        clone_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        created_at: string;
        default_branch: string;
        deployments_url: string;
        description: null | string;
        disabled: boolean;
        downloads_url: string;
        events_url: string;
        fork: boolean;
        forks: number;
        forks_count: number;
        forks_url: string;
        full_name: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        has_discussions: boolean;
        has_downloads: boolean;
        has_issues: boolean;
        has_pages: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        homepage: string;
        hooks_url: string;
        html_url: string;
        id: number;
        is_template: boolean;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        language: string;
        languages_url: string;
        license: null;
        merges_url: string;
        milestones_url: string;
        mirror_url: null;
        name: string;
        node_id: string;
        notifications_url: string;
        open_issues: number;
        open_issues_count: number;
        owner: {
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string;
            // other owner properties
        };
        permissions: {
            admin: boolean;
            maintain: boolean;
            push: boolean;
            triage: boolean;
            pull: boolean;
        };
        private: boolean;
        pulls_url: string;
        pushed_at: string;
        releases_url: string;
        size: number;
        ssh_url: string;
        stargazers_count: number;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        svn_url: string;
        tags_url: string;
        teams_url: string;
        topics: string[];
        trees_url: string;
        updated_at: string;
        url: string;
        visibility: string;
        watchers: number;
        watchers_count: number;
        web_commit_signoff_required: boolean;
    }
   export interface LanguageColors {
        JavaScript: string,
        TypeScript: string,
        CSS: string,
        HTML: string,
        Python: string,
        Java: string,
        C: string,
        'C++': string,
        Ruby: string,
        Go: string,
        Swift: string,
        Rust: string,
        PHP: string,
        Shell: string,
        Perl: string,
        Scala: string,
        Kotlin: string,
        'Objective-C': string,
        'C#': string,
        R: string,
        'Visual Basic': string,
        MATLAB: string,
        Lua: string,
        'TypeScript(JSX)': string,
        'CoffeeScript': string,
        'Vue.js': string,
        'Angular': string,
        'ShellSession': string,
        PowerShell: string,
        Batchfile: string,
        Groovy: string,
    };
}
